# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedencia_alumn', models.CharField(blank=True, max_length=25, null=True, verbose_name='Procedencia del Alumno')),
                ('plantel_retiro_alumn', models.CharField(blank=True, max_length=25, null=True, verbose_name='Plantel de Retiro el Alumno')),
                ('lugar_habi_alumn', models.CharField(blank=True, max_length=25, null=True, verbose_name='Lugar donde vive el Alumno')),
                ('punto_referencia_alumn', models.CharField(blank=True, max_length=25, null=True, verbose_name='Punto de Referencia del Alumno')),
                ('religion', models.CharField(choices=[(b'Catolico', b'Catolico'), (b'Cristiano', b'Cristiano'), (b'Ateo', b'Ateo'), (b'---------', b'---------')], max_length=45, verbose_name='Religi\xf3n')),
                ('cedula_escolar', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitantes.Representante')),
                ('codigo_hab', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitantes.Habitantes')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('codigo_enfermedad', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de la Enfermedad')),
                ('nombres_enfermedad', models.CharField(max_length=25, null=True, verbose_name='Nombre(s) de la(s) Enfermedad(es)')),
                ('descripcion_enfermedad', models.TextField(max_length=100, null=True, verbose_name='Descripci\xf3n de las Enfermedad(es)')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad_alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_enfer', models.DateField(null=True, verbose_name='Fecha de padesimiento de la Enfermedad')),
                ('cedula_escolar', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno')),
                ('codigo_enfermedad', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.Enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('cod_inscri', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscrip', models.DateField(auto_now=True)),
                ('talla_pantalon', models.CharField(choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'Otros', b'Otros'), (b'---------', b'---------')], max_length=45, verbose_name='Talla Pantal\xf3n')),
                ('talla_franela', models.CharField(choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'Otros', b'Otros'), (b'---------', b'---------')], max_length=45, verbose_name='Talla Franela')),
                ('talla_Zapato', models.CharField(choices=[(b'20', b'20'), (b'21', b'21'), (b'22', b'22'), (b'23', b'23'), (b'24', b'24'), (b'25', b'25'), (b'26', b'26'), (b'27', b'27'), (b'28', b'28'), (b'29', b'29'), (b'30', b'30'), (b'31', b'31'), (b'32', b'32'), (b'33', b'33'), (b'34', b'34'), (b'35', b'35'), (b'Otros', b'Otros'), (b'---------', b'---------')], max_length=45, verbose_name='Talla Zapato')),
                ('beca_estudiantil', models.BooleanField(default=False, verbose_name='\xbfPosee Beca Estudiantil?')),
                ('ano_escolar', models.CharField(choices=[(b'2017-2018', b'2017-2018'), (b'2017-2018', b'2017-2018'), (b'2019-2020', b'2018-2019'), (b'2019-2020', b'2018-2019'), (b'2019-2020', b'2019-2020'), (b'2019-2020', b'2019-2020'), (b'2020-2021', b'2020-2021'), (b'2020-2021', b'2020-2021'), (b'2021-2022', b'2021-2022'), (b'2021-2022', b'2021-2022'), (b'2022-2023', b'2022-2023'), (b'2022-2023', b'2022-2023'), (b'2023-2024', b'2023-2024'), (b'2023-2024', b'2023-2024'), (b'2024-2025', b'2024-2025'), (b'2024-2025', b'2024-2025'), (b'2025-2026', b'2025-2026'), (b'2025-2026', b'2025-2026'), (b'Otros', b'Otros'), (b'---------', b'---------')], max_length=45, verbose_name='A\xf1o Escolar')),
                ('cedula_escolar', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('codigo_prof', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del Profesor')),
                ('turno', models.CharField(choices=[(b'Ma\xc3\xb1ana', b'Ma\xc3\xb1ana'), (b'Tarde', b'Tarde'), (b'---------', b'---------')], max_length=45, verbose_name='Turno')),
                ('especialidad_prof', models.CharField(blank=True, max_length=25, null=True, verbose_name='Especialidad del Profesor')),
                ('fecha_ingreso', models.DateField(null=True, verbose_name='Fecha del Ingreso del Profesor')),
                ('codigo_hab', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitantes.Habitantes')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('codigo_seccion', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de la Secci\xf3n')),
                ('turno', models.CharField(choices=[(b'Ma\xc3\xb1ana', b'Ma\xc3\xb1ana'), (b'Tarde', b'Tarde'), (b'---------', b'---------')], max_length=45, verbose_name='Turno')),
                ('seccion', models.CharField(choices=[(b'A', b'A'), (b'B', b'B'), (b'C', b'C'), (b'D', b'D'), (b'E', b'E'), (b'F', b'F'), (b'---------', b'---------')], max_length=45, verbose_name='Secci\xf3n')),
                ('grado', models.CharField(choices=[(b'1ro.', b'1ro.'), (b'2do.', b'2do.'), (b'3ro.', b'3ro.'), (b'---------', b'---------')], max_length=45, verbose_name='Grado')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion_profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_prof', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.Profesor')),
                ('codigo_seccion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.Seccion')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='codigo_seccion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.Seccion'),
        ),
    ]
