# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('codigo_bene', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del Beneficio')),
                ('nombre_bene', models.CharField(max_length=25, null=True, verbose_name='Nombre del Beneficio')),
                ('descripcion_bene', models.TextField(max_length=100, null=True, verbose_name='Descripci\xf3n del Beneficio')),
                ('stock', models.PositiveSmallIntegerField(verbose_name='Stock')),
                ('disponibilidad', models.CharField(max_length=100, null=True, verbose_name='Disponibilidad')),
                ('fecha_ingreso', models.DateField(auto_now=True, verbose_name='Fecha de Ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('codigo_dona', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Donaci\xf3n')),
                ('cedula_ings', models.CharField(max_length=8, unique=True, verbose_name='Cedula del Ing supervisor de la Donaci\xf3n')),
                ('apellidos_ing_sup_do', models.CharField(max_length=100, null=True, verbose_name='Apellidos del Ing supervisor de la Donaci\xf3n')),
                ('nombres_ing_sup_do', models.CharField(max_length=100, null=True, verbose_name='Nombres del Ing supervisor de la Donaci\xf3n')),
                ('cedula_voc_sup_do', models.CharField(max_length=8, unique=True, verbose_name='Cedula del Vocero supervisor de la Donaci\xf3n')),
                ('apellidos_voc_sup_do', models.CharField(max_length=100, null=True, verbose_name='Apellidos del Vocero supervisor de la Donaci\xf3n')),
                ('nombres_voc_sup_do', models.CharField(max_length=100, null=True, verbose_name='Nombres del Vocero supervisor de la Donaci\xf3n')),
                ('fecha_dona', models.DateField(max_length=100, verbose_name='Fecha de la Donaci\xf3n')),
                ('codigo_bene', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitantes.Beneficios')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('codigo_entre', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de la Entrega')),
                ('cantidad_entrega', models.IntegerField(null=True, verbose_name='Cantidad de Beneficio(s) Entregado(s)')),
                ('fecha_entrega', models.DateField(null=True, verbose_name='Fecha de la(s) Entrega(s)')),
                ('cedula_ing', models.CharField(max_length=8, unique=True, verbose_name='Cedula del Ingeniero')),
                ('apellidos_ing', models.CharField(max_length=45, null=True, verbose_name='Apellidos del Ingeniero')),
                ('nombres_ing', models.CharField(max_length=45, null=True, verbose_name='Nombres del Ingeniero')),
                ('cedula_voc1', models.CharField(max_length=8, unique=True, verbose_name='Cedula del Vocero n\xb01')),
                ('apellidos_voc1', models.CharField(max_length=45, null=True, verbose_name='Apellidos del Vocero n\xb01')),
                ('nombres_voc1', models.CharField(max_length=45, null=True, verbose_name='Nombres del Vocero n\xb01')),
                ('cedula_voc2', models.CharField(max_length=8, unique=True, verbose_name='Cedula del Vocero n\xb02')),
                ('apellidos_voc2', models.CharField(max_length=45, null=True, verbose_name='Apellidos del Vocero n\xb02')),
                ('nombres_voc2', models.CharField(max_length=45, null=True, verbose_name='Nombres del Vocero n\xb02')),
                ('cedula_voc3', models.CharField(max_length=8, unique=True, verbose_name='Cedula del Vocero n\xb03')),
                ('apellidos_voc3', models.CharField(max_length=45, null=True, verbose_name='Apellidos del Vocero n\xb03')),
                ('nombres_voc3', models.CharField(max_length=45, null=True, verbose_name='Nombres del Vocero n\xb03')),
            ],
        ),
        migrations.CreateModel(
            name='Habitantes',
            fields=[
                ('codigo_hab', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del habitante')),
                ('cedula_hab', models.CharField(max_length=8, unique=True, verbose_name='Cedula')),
                ('numero_fam', models.CharField(default=0, max_length=3, verbose_name='Numero de Familia')),
                ('nombres', models.CharField(max_length=30, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=30, null=True, verbose_name='Apellidos')),
                ('estados', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estados')),
                ('municipios', models.CharField(blank=True, max_length=30, null=True, verbose_name='Municipios')),
                ('parroquias', models.CharField(blank=True, max_length=30, null=True, verbose_name='Parroquias')),
                ('fecha_habi', models.DateField(max_length=100, verbose_name='Fecha de nacimiento')),
                ('parentesco_hab', models.CharField(blank=True, choices=[(b'Madre', b'Madre'), (b'Padre', b'Padre'), (b'Hijo(a)', b'Hijo(a)'), (b'Tio(a)', b'Tio(a)'), (b'Hermano(a)', b'Hermano(a)'), (b'Abuelo(a)', b'Abuelo(a)'), (b'Otros(as)', b'Otros(as)'), (b'---------', b'---------')], max_length=20, verbose_name='Parentesco del Habitante')),
                ('cod_tel', models.CharField(blank=True, choices=[(b'0257', b'0257'), (b'---------', b'---------')], max_length=45, verbose_name='Codigo del Telefono')),
                ('telef_hab', models.CharField(blank=True, max_length=8, verbose_name='Telefono')),
                ('codigo_movil', models.CharField(blank=True, choices=[(b'0426', b'0426'), (b'0416', b'0416'), (b'0424', b'0424'), (b'0414', b'0414'), (b'0412', b'0412'), (b'---------', b'---------')], max_length=45, verbose_name='Codigo del Movil')),
                ('movil_hab', models.CharField(blank=True, max_length=7, verbose_name='Movil')),
                ('genero_hab', models.CharField(blank=True, choices=[(b'M', b'M'), (b'F', b'F'), (b'---------', b'---------')], max_length=45, verbose_name='Genero')),
                ('toalla_hab', models.NullBooleanField(default=False, verbose_name='\xbfUtiliza Toalla?')),
                ('panal_hab', models.NullBooleanField(default=False, verbose_name='\xbfUtiliza Pa\xf1al?')),
                ('ocupacion_hab', models.CharField(blank=True, choices=[(b'Comerciante', b'Comerciante'), (b'Barbero', b'Barbero'), (b'Estudiante', b'Estudiante'), (b'Empleado(a)', b'Empleado(a)'), (b'Jubilado(a)', b'Jubilado(a)'), (b'Tecnico', b'Tecnico'), (b'Pensionado(a)', b'Pensionado(a)'), (b'Obrero(a)', b'Obrero(a)'), (b'Educador(a)', b'Educador(a)'), (b'Pastor(a)', b'Pastor(a)'), (b'Herrero', b'Herrero'), (b'Maternal', b'Maternal'), (b'Soldador', b'Soldador'), (b'Estilita', b'Estilita'), (b'Manicurista', b'Manicurista'), (b'Ama(o) de casa', b'Ama(o) de casa'), (b'Nutricionista', b'Nutricionista'), (b'Obrero(a) Educacional', b'Obrero(a) Educacional'), (b'Contador', b'Contador'), (b'Cocinero(a)', b'Cocinero(a)'), (b'Policia', b'Policia'), (b'Administrador(ar)', b'Administrador(ar)'), (b'Promotor(a) Social', b'Promotor(a) Social'), (b'Docente', b'Docente'), (b'Custodio', b'Custodio'), (b'Pencionado(a)', b'Pencionado(a)'), (b'Mecanico', b'Mecanico'), (b'Abogado(a)', b'Abogado(a)'), (b'Chofer', b'Chofer'), (b'Empleado(a) Publico', b'Empleado(a) Publico'), (b'Laboratorista', b'Laboratorista'), (b'Peluquero(a)', b'Peluquero(a)'), (b'Educador(a)', b'Educador(a)'), (b'Agricultor(a)', b'Agricultor(a)'), (b'TSU', b'TSU'), (b'Enfermero(a)', b'Enfermero(a)'), (b'Carpintero(a)', b'Carpintero(a)'), (b'Ambientalista', b'Ambientalista'), (b'Militar', b'Militar'), (b'Alba\xc3\xb1il', b'Alba\xc3\xb1il'), (b'Secretaria(o)', b'Secretaria(o)'), (b'Deportista', b'Deportista'), (b'Vigilante', b'Vigilante'), (b'Costurera', b'Costurera'), (b'Discapacidad', b'Discapacidad'), (b'Camarera(o)', b'Camarera(o)'), (b'Luc. social', b'Luc. social'), (b'Ejecutivo(a) Bancaria', b'Ejecutivo(a) Bancaria'), (b'Otros(as)', b'Otros(as)'), (b'---------', b'---------')], max_length=20, verbose_name='Ocupaci\xf3n del Habitante')),
                ('direccion', models.TextField(blank=True, max_length=100, null=True, verbose_name='Direcci\xf3n del Habitante')),
                ('tipo_propiedad_hab', models.CharField(blank=True, choices=[(b'Propia', b'Propia'), (b'Arquilada', b'Arquilada'), (b'---------', b'---------')], max_length=45, verbose_name='Tipo de Propiedad')),
                ('correo', models.EmailField(blank=True, max_length=70, verbose_name='Correo electronico')),
                ('consejoc_pert', models.CharField(choices=[(b'1', b'1'), (b'2', b'2'), (b'---------', b'---------')], max_length=45, verbose_name='Consejo comunal que pertenece')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('codigo_inspe', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Inspecci\xf3n')),
                ('cedula_ing_ins', models.CharField(blank=True, max_length=8, null=True, verbose_name='Cedula del Ing Supervisor')),
                ('apellidos_ing', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos del Ing supervisor')),
                ('nombres_ing_ins', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombres del Ing supervisor')),
                ('cedula_voc', models.CharField(blank=True, max_length=8, null=True, verbose_name='Cedula del Vocero')),
                ('apellidos_voc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos del Vocero')),
                ('nombres_voc', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombres del Vocero')),
                ('coodenada_uml', models.CharField(blank=True, max_length=45, null=True, verbose_name='Coordenada UML')),
                ('topologia_vivienda', models.CharField(blank=True, max_length=45, null=True, verbose_name='Topologia de Vivienda')),
                ('tipo_proyecto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Proyecto')),
                ('observacion', models.TextField(blank=True, max_length=100, null=True, verbose_name='Observaci\xf3n')),
                ('fecha_inspeccion', models.DateField(max_length=100, verbose_name='Fecha de Inspecci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('codigo_representa', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del Representante')),
                ('cedula_escolar', models.CharField(max_length=8, unique=True, verbose_name='Cedula Escolar')),
                ('paren_representa', models.CharField(choices=[(b'Madre', b'Madre'), (b'Padre', b'Padre'), (b'Hijo(a)', b'Hijo(a)'), (b'Tio(a)', b'Tio(a)'), (b'Hermano(a)', b'Hermano(a)'), (b'Abuelo(a)', b'Abuelo(a)'), (b'Otros(as)', b'Otros(as)'), (b'---------', b'---------')], max_length=45, verbose_name='Parentesco del Representante')),
                ('codigo_hab', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitantes.Habitantes')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('codigo_solici', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Solicitud')),
                ('cantidad_bene', models.IntegerField(default=0, null=True, verbose_name='Cantidad del Beneficio')),
                ('cantidad_probado', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de beneficios Aprobados')),
                ('fecha_solici', models.DateTimeField(auto_now=True, verbose_name='Fecha de la Solicitud')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('codigo_bene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitantes.Beneficios')),
                ('codigo_hab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitantes.Habitantes')),
            ],
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('codigo_super', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de la supervici\xf3n')),
                ('cedula_ing_sup_do', models.CharField(max_length=8, unique=True, verbose_name='Cedula del Ing supervici\xf3n Donaci\xf3n')),
                ('apellidos_ing_sup_do', models.CharField(max_length=45, null=True, verbose_name='Apellidos del Ing supervisor Donaci\xf3n')),
                ('nombres_ing_sup_do', models.CharField(max_length=45, null=True, verbose_name='Nombres del Ing supervisor de la Donaci\xf3n')),
                ('cedula_voc_sup_do', models.CharField(max_length=8, unique=True, verbose_name='Cedula del Vocero Supervisor de la Donaci\xf3n')),
                ('apellidos_voc_sup_do', models.CharField(max_length=45, null=True, verbose_name='Apellidos del Vocero Supervisor de la Donaci\xf3n')),
                ('nombres_voc_sup_do', models.CharField(max_length=45, null=True, verbose_name='Nombres del Vocero Supervisor de la Donaci\xf3n')),
                ('lugar_entre', models.CharField(max_length=45, null=True, verbose_name='Lugar de la entrega')),
                ('descrip_luga', models.TextField(blank=True, max_length=100, null=True, verbose_name='Descripci\xf3n del lugar de la Entrega')),
                ('cantida_bene', models.IntegerField(null=True, verbose_name='Cantidad de Beneficio(s)')),
                ('fecha_super', models.DateField(null=True, verbose_name='Fecha de la supervisi\xf3n')),
                ('codigo_bene', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitantes.Beneficios')),
            ],
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='codigo_solici',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitantes.Solicitud'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='codigo_solici',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitantes.Solicitud'),
        ),
    ]
