# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_comerciante',
        ),
        migrations.AddField(
            model_name='account',
            name='is_coordinador',
            field=models.BooleanField(default=False, verbose_name='coordinador'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_representante',
            field=models.BooleanField(default=False, verbose_name='representante'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_voceros',
            field=models.BooleanField(default=False, verbose_name='voceros'),
        ),
    ]
