# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170527_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_voceros',
            new_name='is_vocero',
        ),
    ]
